name: build nonprod

on:
  push:
    branches:
      - dev

jobs:
  build_nonprod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: set env image name
        run: |-
          echo "DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV;
          echo "DOCKER_IMAGE=app1-webui" >> $GITHUB_ENV;
      
      - name: automated version bump
        id: versioning
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v1.'
          major-wording:  'MAJOR,major'
          minor-wording:  'MINOR,minor'
          patch-wording:  'PATCH,patch'
          rc-wording:     'pre-dev,pre-sit,pre-uat,pre-preprod'
          default: prerelease
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

      - name: set env tag
        env: 
          NEW_TAG: ${{ steps.versioning.outputs.newTag }} 
        run: |
            echo "curent build tag/release is $NEW_TAG"
            echo ${{ steps.versioning.outputs.newTag }}
            echo "TAG=$(echo ${{ steps.versioning.outputs.newTag }} | sed 's/v//')" >> $GITHUB_ENV;

      - name: image build with kaniko
        if: env.TAG != ''
        uses: aevea/action-kaniko@master
        with:
          image: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}
          tag: ${{ env.TAG }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: false
          cache_registry: ${{ env.DOCKER_USERNAME }}/cache

      - name: trivy vulnerability scanner
        if: env.TAG != ''      
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.TAG }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: set output imagename
        id: imagename_output
        run: echo "image_name=${{ env.DOCKER_IMAGE }}:${{ env.TAG }}" >> "$GITHUB_OUTPUT"
      
    outputs:
      image_name: ${{ steps.imagename_output.outputs.image_name }}
      tag_version: ${{ env.TAG }}
      build_type: "nonprod"

  update_manifest:
    needs: build_nonprod
    uses: ./.github/workflows/update_manifest.yml
    with:
      imagename: ${{ needs.build_nonprod.outputs.image_name }}
      repository: nuttapornk/App1-Deployment
      domain_name: app1-webui
      tag_version: ${{ needs.build_nonprod.outputs.tag_version }}
      build_type: ${{ needs.build_nonprod.outputs.build_type }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
