name: ci

on:
  push:
    branches:
      - dev
      - uat
      - preprod
      - main
permissions:
  contents: write
  packages: write

jobs:
  workflow_call_build:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}      

  update_manifest:
    needs: workflow_call_build
    uses: ./.github/workflows/update_manifest.yml
    with:
      imagename: ${{ needs.workflow_call_build.outputs.imagename }}      
      repository: nuttapornk/app1-deployment           
      domain_name: app1-webui
    secrets:
      my_pat: ${{ secrets.MY_PAT }}