name: update_manifest

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
      repository:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      my_pat:
        required: true

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: "${{inputs.repository}}"
          ref: "nonprod"
          token: ${{ secrets.my_pat }}
      - name: Set variable
        run: |-
          echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - name: Is dev?
        if: env.BRANCH == 'dev'
        run: echo "DIR=dev" >> $GITHUB_ENV;
      - name: Is develop?
        if: env.BRANCH == 'develop'
        run: echo "DIR=dev" >> $GITHUB_ENV;
      - name: Is sit?
        if: env.BRANCH == 'sit'
        run: echo "DIR=sit" >> $GITHUB_ENV;
      - name: Is uat?
        if: env.BRANCH == 'uat'
        run: echo "DIR=uat" >> $GITHUB_ENV;
      - name: Is preprod?
        if: env.BRANCH == 'preprod'
        run: echo "DIR=preprod" >> $GITHUB_ENV;
      - name: Is main?
        if: env.BRANCH == 'main'
        run: echo "DIR=production" >> $GITHUB_ENV;
      - name: Is master?
        if: env.BRANCH == 'master'
        run: echo "DIR=production" >> $GITHUB_ENV;
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Set Tag
        run: |
          echo "TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
          echo ${{ inputs.imagename }};

      - name: Patch kustomize
        run: |-
          ls -la src/microservices/onprem/${{ inputs.app_name }}/env/${{ env.DIR }}
          cd src/microservices/onprem/${{ inputs.app_name }}/env/${{ env.DIR }}
          echo "kustomize update src/microservices/onprem/${{ inputs.app_name }}/env/${{ env.DIR }}"          
          kustomize edit set image ${{ env.DOCKER_IMAGE }}
          cat kustomization.yaml

      - name: Push update manifest to deployment repo
        run: |
          echo "REPO_NAME=${{ inputs.repository }}" >> $GITHUB_ENV
          ls
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update manifest ${{ env.DOCKER_IMAGE }}"
          git push    